version: '3.8'

services:
  postgres:
    image: postgres         #coming from hub.docker.com
    ports:
      - '5432:5432'
    environment :
      POSTGRES_USER : postgres
      POSTGRES_DB : docker
      POSTGRES_PASSWORD : postgres

  redis :
    image : 'redis'
    ports:
      - '6379:6379'

